name: build_macos

on:
  push:
    branches:
      - "*"

jobs:
  main:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Fetch VTK sources
      run: |
        curl -OL https://www.vtk.org/files/release/9.3/VTK-9.3.0.rc2.tar.gz
        tar xzvf VTK-9.3.0.rc2.tar.gz

    - name: Create & configure VTK build directory
      run: |
        cd VTK-9.3.0.rc2
        mkdir build && cd build
        cmake \
        -DCMAKE_INSTALL_RPATH=/usr/local/lib \
        -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
        -DCMAKE_BUILD_TYPE=Debug \
        ..

    - name: Build & install VTK
      run: |
        cd VTK-9.3.0.rc2
        cmake --build build --target install --parallel

    - name: Create & configure build directory
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE

    - name: Build
      run: |
        cmake --build build

    - name: Test binary
      run: |
        otool -L build/main
        build/main
